import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#05070e',
  },
  background: {
    ...StyleSheet.absoluteFillObject,
    overflow: 'hidden',
  },
  glow: {
    position: 'absolute',
    borderRadius: 999,
    opacity: 0.5,
  },
  glowPink: {
    width: 420,
    height: 420,
    top: -180,
    left: -80,
    backgroundColor: '#ff174d',
  },
  glowBlue: {
    width: 280,
    height: 280,
    top: 210,
    right: -150,
    backgroundColor: '#284e9f',
  },
  ghostWord: {
    position: 'absolute',
    bottom: 78,
    left: 18,
    color: 'rgba(255,255,255,0.08)',
    fontSize: 118,
    fontWeight: '900',
    letterSpacing: 0,
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 58,
    paddingHorizontal: 18,
    paddingBottom: 118,
  },
  header: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  brandRow: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 9,
  },
  brandMark: {
    alignItems: 'center',
    backgroundColor: '#ff316f',
    borderRadius: 18,
    height: 34,
    justifyContent: 'center',
    width: 34,
  },
  brandMarkText: {
    color: '#fff',
    fontSize: 16,
    fontWeight: '900',
  },
  brand: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '800',
  },
  headerActions: {
    flexDirection: 'row',
    gap: 10,
  },
  iconButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.08)',
    borderColor: 'rgba(255,255,255,0.12)',
    borderRadius: 18,
    borderWidth: 1,
    height: 36,
    justifyContent: 'center',
    width: 36,
  },
  iconButtonText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  permissionCard: {
    alignItems: 'center',
    backgroundColor: '#0c1428',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 16,
    padding: 14,
  },
  permissionTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  permissionText: {
    color: '#8d9abb',
    fontSize: 11,
    lineHeight: 16,
    marginTop: 4,
    maxWidth: 210,
  },
  permissionButton: {
    backgroundColor: '#ff316f',
    borderRadius: 18,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  permissionButtonText: {
    color: '#ffffff',
    fontSize: 11,
    fontWeight: '900',
  },
  libraryGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  libraryCard: {
    backgroundColor: '#0c1428',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    borderWidth: 1,
    minHeight: 112,
    padding: 16,
    width: '48%',
  },
  libraryIcon: {
    alignItems: 'center',
    borderRadius: 18,
    height: 34,
    justifyContent: 'center',
    marginBottom: 16,
    width: 34,
  },
  libraryIconText: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '900',
  },
  libraryTitle: {
    color: '#ffffff',
    fontSize: 14,
    fontWeight: '800',
  },
  libraryCount: {
    color: '#7f8ba6',
    fontSize: 11,
    marginTop: 4,
  },
  sectionHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 10,
    marginTop: 22,
  },
  sectionTitle: {
    color: '#aab5cf',
    fontSize: 14,
    fontWeight: '700',
  },
  sectionMeta: {
    color: '#687594',
    fontSize: 12,
    fontWeight: '700',
  },
  sectionAction: {
    color: '#ff6a98',
    fontSize: 12,
    fontWeight: '800',
  },
  folderList: {
    backgroundColor: '#0c1428',
    borderRadius: 8,
    overflow: 'hidden',
  },
  folderRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingHorizontal: 14,
    paddingVertical: 12,
  },
  folderIcon: {
    borderRadius: 4,
    height: 18,
    marginRight: 12,
    width: 23,
  },
  folderCopy: {
    flex: 1,
  },
  folderName: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  folderCount: {
    color: '#687594',
    fontSize: 10,
    marginTop: 3,
  },
  more: {
    color: '#d7deef',
    fontSize: 16,
    fontWeight: '900',
    letterSpacing: 0,
  },
  videoList: {
    gap: 10,
  },
  videoRow: {
    alignItems: 'center',
    backgroundColor: '#0c1428',
    borderColor: 'rgba(255,255,255,0.06)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    padding: 10,
  },
  videoRowActive: {
    borderColor: 'rgba(255,49,111,0.9)',
  },
  thumbnail: {
    alignItems: 'center',
    backgroundColor: '#101b35',
    borderRadius: 6,
    height: 62,
    justifyContent: 'center',
    marginRight: 12,
    overflow: 'hidden',
    width: 86,
  },
  thumbGlow: {
    borderRadius: 45,
    height: 90,
    opacity: 0.75,
    position: 'absolute',
    right: -25,
    top: -20,
    width: 90,
  },
  thumbnailPlay: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  videoCopy: {
    flex: 1,
  },
  videoName: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
    lineHeight: 17,
  },
  videoLocation: {
    color: '#8290ad',
    fontSize: 11,
    marginTop: 3,
  },
  videoPills: {
    flexDirection: 'row',
    gap: 6,
    marginTop: 7,
  },
  videoPill: {
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 4,
    color: '#aab5cf',
    fontSize: 9,
    fontWeight: '800',
    overflow: 'hidden',
    paddingHorizontal: 6,
    paddingVertical: 3,
  },
  favoriteMark: {
    color: '#aeb9d6',
    fontSize: 24,
    fontWeight: '900',
    paddingHorizontal: 4,
  },
  favoriteMarkActive: {
    color: '#ff316f',
  },
  pageTitleBlock: {
    marginBottom: 18,
  },
  pageTitle: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '900',
  },
  pageSubtitle: {
    color: '#9aa7c5',
    fontSize: 13,
    fontWeight: '600',
    marginTop: 6,
  },
  emptyState: {
    alignItems: 'center',
    backgroundColor: '#0c1428',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    borderWidth: 1,
    paddingHorizontal: 18,
    paddingVertical: 36,
  },
  emptyTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  emptyText: {
    color: '#8d9abb',
    fontSize: 13,
    marginTop: 8,
    textAlign: 'center',
  },
  modeSwitch: {
    backgroundColor: '#0c1428',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 8,
    borderWidth: 1,
    flexDirection: 'row',
    gap: 8,
    marginBottom: 16,
    padding: 6,
  },
  modeButton: {
    alignItems: 'center',
    borderRadius: 7,
    flex: 1,
    paddingVertical: 11,
  },
  modeButtonActive: {
    backgroundColor: '#ff316f',
  },
  modeText: {
    color: '#9aa7c5',
    fontSize: 12,
    fontWeight: '900',
  },
  modeTextActive: {
    color: '#ffffff',
  },
  heroShell: {
    backgroundColor: '#10172a',
    borderColor: 'rgba(255,255,255,0.16)',
    borderRadius: 34,
    borderWidth: 1,
    minHeight: 520,
    overflow: 'hidden',
    padding: 10,
  },
  notch: {
    alignSelf: 'center',
    backgroundColor: '#02040b',
    borderBottomLeftRadius: 14,
    borderBottomRightRadius: 14,
    height: 24,
    position: 'absolute',
    top: 12,
    width: 90,
    zIndex: 5,
  },
  heroArt: {
    backgroundColor: '#ff2365',
    borderRadius: 27,
    height: 260,
    overflow: 'hidden',
  },
  audioArt: {
    backgroundColor: '#5d94ff',
  },
  videoSurface: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: '#02040b',
  },
  ray: {
    backgroundColor: 'rgba(9,14,31,0.72)',
    height: 170,
    position: 'absolute',
    width: 90,
    zIndex: 1,
  },
  rayOne: {
    left: 30,
    top: -20,
    transform: [{ rotate: '-16deg' }],
  },
  rayTwo: {
    right: 28,
    top: -30,
    transform: [{ rotate: '28deg' }],
  },
  rayThree: {
    bottom: -56,
    left: 20,
    transform: [{ rotate: '64deg' }],
  },
  videoPreview: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(5,8,18,0.18)',
    opacity: 0.7,
    zIndex: 2,
  },
  previewHorizon: {
    backgroundColor: 'rgba(255,255,255,0.16)',
    bottom: 72,
    height: 2,
    left: 38,
    position: 'absolute',
    right: 38,
  },
  previewBuildingTall: {
    backgroundColor: 'rgba(8,12,28,0.64)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    bottom: 72,
    height: 84,
    left: 54,
    position: 'absolute',
    width: 44,
  },
  previewBuildingShort: {
    backgroundColor: 'rgba(8,12,28,0.52)',
    borderTopLeftRadius: 4,
    borderTopRightRadius: 4,
    bottom: 72,
    height: 58,
    right: 62,
    position: 'absolute',
    width: 58,
  },
  previewRoad: {
    alignSelf: 'center',
    backgroundColor: 'rgba(10,14,30,0.48)',
    borderTopLeftRadius: 80,
    borderTopRightRadius: 80,
    bottom: -74,
    height: 150,
    position: 'absolute',
    width: 190,
  },
  previewLabel: {
    bottom: 24,
    color: 'rgba(255,255,255,0.8)',
    fontSize: 12,
    fontWeight: '800',
    left: 0,
    position: 'absolute',
    right: 0,
    textAlign: 'center',
    textTransform: 'uppercase',
  },
  playOrb: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: 'rgba(255,255,255,0.22)',
    borderColor: 'rgba(255,255,255,0.25)',
    borderRadius: 54,
    borderWidth: 1,
    height: 108,
    justifyContent: 'center',
    position: 'absolute',
    top: 80,
    width: 108,
    zIndex: 3,
  },
  playOrbText: {
    color: '#ff2f6d',
    fontSize: 35,
    fontWeight: '900',
    marginLeft: 4,
  },
  heroInfo: {
    alignItems: 'center',
    paddingHorizontal: 18,
    paddingTop: 24,
  },
  pager: {
    flexDirection: 'row',
    gap: 5,
    marginBottom: 18,
  },
  pagerDot: {
    backgroundColor: '#ffffff',
    borderRadius: 4,
    height: 7,
    opacity: 0.9,
    width: 7,
  },
  pagerDotActive: {
    backgroundColor: '#ff316f',
    width: 22,
  },
  heroTitle: {
    color: '#ffffff',
    fontSize: 36,
    fontWeight: '900',
    letterSpacing: 0,
    lineHeight: 42,
    textAlign: 'center',
  },
  heroTitleCompact: {
    fontSize: 31,
    lineHeight: 37,
  },
  heroSubtitle: {
    color: '#dfe7ff',
    fontSize: 13,
    marginTop: 14,
    textAlign: 'center',
  },
  timeline: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 10,
    marginTop: 22,
    width: '100%',
  },
  timeText: {
    color: '#9aa7c5',
    fontSize: 11,
    fontWeight: '700',
    width: 42,
  },
  progressTrack: {
    backgroundColor: 'rgba(255,255,255,0.1)',
    borderRadius: 6,
    flex: 1,
    height: 6,
    overflow: 'hidden',
  },
  progressFill: {
    backgroundColor: '#ff316f',
    borderRadius: 6,
    height: '100%',
  },
  heroControls: {
    alignItems: 'center',
    flexDirection: 'row',
    gap: 12,
    justifyContent: 'center',
    marginTop: 22,
    width: '100%',
  },
  smallRoundButton: {
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderRadius: 17,
    height: 34,
    justifyContent: 'center',
    width: 42,
  },
  smallRoundText: {
    color: '#d6def5',
    fontSize: 11,
    fontWeight: '800',
  },
  primaryControl: {
    alignItems: 'center',
    backgroundColor: '#0b1122',
    borderRadius: 23,
    height: 46,
    justifyContent: 'center',
    width: 46,
  },
  primaryControlText: {
    color: '#ffffff',
    fontSize: 28,
    fontWeight: '500',
  },
  mainControl: {
    alignItems: 'center',
    backgroundColor: '#ff316f',
    borderRadius: 29,
    height: 58,
    justifyContent: 'center',
    width: 58,
  },
  mainControlText: {
    color: '#ffffff',
    fontSize: 20,
    fontWeight: '900',
  },
  bottomNav: {
    alignItems: 'center',
    alignSelf: 'center',
    backgroundColor: '#111a31',
    borderColor: 'rgba(139,154,193,0.18)',
    borderRadius: 28,
    borderWidth: 1,
    bottom: 0,
    flexDirection: 'row',
    height: 64,
    justifyContent: 'center',
    left: 14,
    paddingHorizontal: 12,
    position: 'absolute',
    right: 14,
  },
  navButton: {
    alignItems: 'center',
    borderRadius: 22,
    height: 44,
    justifyContent: 'center',
    marginHorizontal: 18,
    width: 44,
  },
  navButtonActive: {
    backgroundColor: '#ff316f',
  },
  navIcon: {
    color: '#aeb9d6',
    fontSize: 27,
    fontWeight: '400',
    lineHeight: 31,
  },
  navIconActive: {
    color: '#ffffff',
    fontWeight: '900',
  },
  modalOverlay: {
    backgroundColor: 'rgba(0,0,0,0.62)',
    flex: 1,
    justifyContent: 'flex-end',
  },
  sheet: {
    backgroundColor: '#0a1123',
    borderTopLeftRadius: 26,
    borderTopRightRadius: 26,
    maxHeight: '76%',
    paddingBottom: 32,
    paddingHorizontal: 18,
    paddingTop: 10,
  },
  sheetHandle: {
    alignSelf: 'center',
    backgroundColor: '#35425f',
    borderRadius: 3,
    height: 5,
    marginBottom: 18,
    width: 46,
  },
  sheetHeader: {
    alignItems: 'center',
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  sheetTitle: {
    color: '#ffffff',
    fontSize: 18,
    fontWeight: '900',
  },
  sheetClose: {
    color: '#ff6a98',
    fontSize: 13,
    fontWeight: '800',
  },
  sheetLabel: {
    color: '#aab5cf',
    fontSize: 12,
    fontWeight: '900',
    marginBottom: 10,
    marginTop: 8,
    textTransform: 'uppercase',
  },
  speedRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
    marginBottom: 12,
  },
  speedButton: {
    backgroundColor: '#121b33',
    borderColor: 'rgba(255,255,255,0.08)',
    borderRadius: 18,
    borderWidth: 1,
    paddingHorizontal: 13,
    paddingVertical: 9,
  },
  speedButtonActive: {
    backgroundColor: '#ff316f',
    borderColor: '#ff316f',
  },
  speedText: {
    color: '#c7d2eb',
    fontSize: 12,
    fontWeight: '800',
  },
  speedTextActive: {
    color: '#ffffff',
  },
  sheetVideoRow: {
    alignItems: 'center',
    borderBottomColor: 'rgba(255,255,255,0.06)',
    borderBottomWidth: 1,
    flexDirection: 'row',
    paddingVertical: 12,
  },
  sheetVideoRowActive: {
    backgroundColor: 'rgba(255,49,111,0.08)',
  },
  sheetVideoIndex: {
    color: '#ff6a98',
    fontSize: 13,
    fontWeight: '900',
    width: 30,
  },
  sheetVideoCopy: {
    flex: 1,
  },
  sheetVideoTitle: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '800',
  },
  sheetVideoMeta: {
    color: '#7f8ba6',
    fontSize: 11,
    marginTop: 3,
  },
  sheetPlaying: {
    color: '#ff6a98',
    fontSize: 11,
    fontWeight: '900',
  },
});
